### ISSUE TITLE
conflict with computercraft EDI

### ISSUE THREAD

**Issue by monkeybee11** [Darkona/AdventureBackpack2#112]
when programing a biggner turtle and use the "item name" thing this crash happens 
the only rasin im posting it here and not at computercraftEDU is
A. cant find there github
B. your name is on the crash report as the problem not theres 

http://pastebin.com/naR6X32d

**Comment by runescapejon** [comment]
is this still a problem ?

**Comment by monkeybee11** [comment]
tbh no clue removed the backpack mod after we found the crash ill have a look in the morning :P

**Comment by runescapejon** [comment]
Mind testing it it here https://github.com/runescapejon/AdventureBackpack2/releases

**Comment by monkeybee11** [comment]
yep still crashing me 
http://pastebin.com/DNud8tMg

**Comment by runescapejon** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb14

**Comment by monkeybee11** [comment]
agen will have a look inthe morning bussy atm :P not being rude but u coud just install computercraft and computercraftEDU your mod give your self a turtle controller place a biggner turtle and place the diamond icon into the gui and see if u get crashed :P

**Comment by runescapejon** [comment]
alright i'll see if i can fix this issue ill get back to you if i fix it or if i need more information

**Comment by runescapejon** [comment]
can you give me more information i don't understand sorry

**Comment by monkeybee11** [comment]
ummm when u open the biggner turtle u have this screen right ? http://computercraftedu.com/img/visual-editor.png
 just placing itemname in to the gui (the diamond buttion)  cause my crash
me am really bad at exsplaning sry >.<

**Comment by runescapejon** [comment]
do you mean Beginner's turtle?

**Comment by runescapejon** [comment]
https://gyazo.com/3fc8b6cc023354c5d59ce2bc39e6a7c5

**Comment by monkeybee11** [comment]
ya thats it sry for my bad spelling :P looks like u fixed it ^_^ ill test it my end when me can anyway jsut to  make sure :P

**Comment by runescapejon** [comment]
is this a public modpack ? so i can see the problem

**Comment by monkeybee11** [comment]
on the curse launcher yes
monkeymagic makesure u download the 1.7.10 verion :3

**Comment by runescapejon** [comment]
Fixed https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.8eb14
just make sure you take out the old AdventureBackpack2 mod

**Comment by monkeybee11** [comment]
oki thx ^_^
