### ISSUE TITLE
Can't craft backpack

### ISSUE THREAD

**Issue by Penetros** [Darkona/AdventureBackpack2#119]
I'm not sure if this is an issue with the VoidsWrath packs that have Adventure Backpack 2 or something else but on both Crusader Craft and Crazy Craft I have been unable to craft the backpack, neither has the other person with me. Looking in the adventurebackpack.cfg file I see no option to turn it off so I'm not exactly sure what's wrong, they all show up in NEI just the standard isn't craftable for some reason.

**Comment by runescapejon** [comment]
can you list the one's that are not craftable?

**Comment by Penetros** [comment]
Nevermind, got it working by deleting the mod and putting it back in. The pack itself had a few other problems but I thought this one was with the mod for some reason, turns out it wasn't.
