### ISSUE TITLE
Bat Backpack Nightvision

### ISSUE THREAD

**Issue by ElvenChaos** [Darkona/AdventureBackpack2#23]
The nightvision given by the bat backpack has a strobing effect. I believe it has something to do with how you are re-applying the potion effect, and I think Botania solved a similar problem with its Ring of Chordata a while back. It might have been a different mod with a different item ;x.

**Comment by Darkona** [comment]
Succesfully replicated, looking for solution.

**Comment by Darkona** [comment]
Still working on a simple way to make this work... but maybe "simple" is not a realistic goal.

**Comment by Darkona** [comment]
Fixed for next version :dart:
