### ISSUE TITLE
Internal server error when hose is crafted

### ISSUE THREAD

**Issue by jayjanicki** [Darkona/AdventureBackpack2#31]
I crafted a hose today on a multiplayer server. When I took the hose off the bench, I was disconnected from server. Then couldn't log back on.  Here's the server console message:
![hose issue](https://cloud.githubusercontent.com/assets/10376009/5600103/8b667d1c-92a1-11e4-9a82-7e3548b5ddd4.png)

**Comment by Darkona** [comment]
Holy crap that is bizarre. I'll take a look.

**Comment by Darkona** [comment]
Fixed, next version will contain this fix.
