### ISSUE TITLE
Internal Server Error when Watermelon juice is drank

### ISSUE THREAD

**Issue by itanshi** [Darkona/AdventureBackpack2#32]
https://github.com/MentatMinions/IndustriaArcanum/blob/master/MODLIST.md
 List of mods also installed

http://paste.feed-the-beast.com/view/f6503f71

**Comment by Darkona** [comment]
As far as I can see it doesn't have anything to do with this mod.
com.teamcos.modularsystems.storage.containers.ContainerModularStorage

**Comment by Darkona** [comment]
Note: that doesn't mean I won't look at it anyway, but it doesn't seem to be my fault so far.
