### ISSUE TITLE
Disappearing backpack after falling in combat

### ISSUE THREAD

**Issue by Maokuma** [Darkona/AdventureBackpack2#37]
Hi, I could not catch this in an error log. But creepers and some other knight mobs from Thaumcraft where able to kill the player and the backpack did not drop to the ground at all or in reach of 16 blocks.

I run the latest forge 1286 (1.7.10) on an dedicated private server using version 0.7.5 of Adventures Backpack. Except Witchery craft, there is no mod using items from death.

/Side note, thanks for making an awesome mod. I have heard many good things about it from friends playing on the server. It's really fun.

**Comment by Darkona** [comment]
This has been fixed for the enxt version.
