### ISSUE TITLE
fluids not rendering in 3d model

### ISSUE THREAD

**Issue by JokerReaper** [Darkona/AdventureBackpack2#48]
its not a game breaking issue, not a big problem but just wanted post it. the tanks while wearing or by putting on the floor arent showing up. idk if its because im using the wrong render setting or anything like that i havent tested it. anyways figured it was worth mentioning. also love the new gui, seeing some great ideas in the new additions keep up the great work :+1:

**Comment by MrabEzreb** [comment]
this happens for me too, except for its not that the liquid doesnt render, its that it renders as if the tank is 1/6 full or that the liquid is a wierd color.

**Comment by Darkona** [comment]
Weird. What fluid are you talking about? is it with something in particular or with all of them?

**Comment by JokerReaper** [comment]
its any fluid water, lava, & melon juice i havent tried any others

**Comment by JokerReaper** [comment]
after i tested & retested various ways of what could be the problem, i changed the render in the config from the default which is 3 to 2, & it solved the issues of it showing up, both as it is on the ground, & on the back of the player, incase someone doesnt know what im talking about:

1: make backups of your worlds & settings because its just a good idea when doing anything like this, incase mistakes are made or just random bugginess.
2: open the config folder, it is in your .minecraft folder. if you do not know how to find the .minecraft folder google it, there are plenty of places that will tell you how.
3: look for the adventurebackpack.cfg file & open it in notepad.
4: look for this line of text "# 1,2 or 3 for different rendering of fluids in the Backpack GUI [range: 1 ~ 3, default: 3]
    I:TankRenderType=3"
5: change the 3 on "I:TankRenderType=3" to 2 & save the file.

if for whatever reason it isnt working, make sure your mod is up to date & your version of  the mod loader is up to date, mine is forge-1.7.10-10.13.2.1230-installer, & it works fine with it. im sorry i do not use any other mod loaders

**Comment by MrabEzreb** [comment]
that is good to know! Thanks!
