### ISSUE TITLE
Make backpack placement on death respect KeepInventory rule

### ISSUE THREAD

**Issue by Darkona** [Darkona/AdventureBackpack2#50]

**Comment by LucidCrux** [comment]
I'd like to second this in an attempt to bump up the priority. Keep Inventory is pretty important for young kids, certain types of maps this would work well with but where areas get reset (the backpack would just be lost), and just for people that play with it on (like if they suck with combat).

**Comment by ShadowDrakken** [comment]
KeepInventory and Soulbound are both ignored *grumbles about vanished backpack*

**Comment by Darkona** [comment]
KeepInventory is now respected.
