### ISSUE TITLE
dragon backpack bug

### ISSUE THREAD

**Issue by JokerReaper** [Darkona/AdventureBackpack2#52]
while playing my single player map, i defeated the ender dragon, got the egg blah blah right. when i made the dragon backpack i knew what it gave you for wearing it, ie: regeneration, fire resistance 3, & strength 2, i havent tested strength 2 to see if it works, but fire resistance only works with fire, not lava, not sure why, might be like what happened with the bat pack some kind of side effect cause it restarting at 0, im only guessing atm

**Comment by Darkona** [comment]
Fixed for Beta-8.0d
