### ISSUE TITLE
DUPLICATION GLITCH

### ISSUE THREAD

**Issue by xaleb** [Darkona/AdventureBackpack2#54]
i came accross a duplication glitch within this mod..using the crafting grid in the backpacks, you can place the items in the correct spots for the recipe,  then close the backpack menu getting the ingredients back, and open the backpack back up and take the crafting item as well..im using zombie pigman bacpack..a suggestion would be make the crafting table storage too so it doesnt drop when u close it..

**Comment by MrabEzreb** [comment]
that wouldn't be a bad idea @xaleb. Sortof like the factorization portable crafting whatever-it's-called. You *can* fill up your entire inventory, but if you do, then you have to clear it if you want to craft on the go. I guess it could be the same with backpacks. You *can* fill up the entire thing, but if you do, then you can't craft in it. Also, it would be very convenient, just like the tinker's construct crafting station. If you are missing something, you can leave the crafting station, get what you need, and when you go back to the crafting station, everything is still there! It could be the same with the backpack crafting grid.

**Comment by Darkona** [comment]
I havent been able to replicate this. However, I placed don't checks to avoid that in case it tries to happen again.

**Comment by xaleb** [comment]
So can I download a newer version, or is it being put together?

**Comment by orionnoir** [comment]
using a pack that includes AventureBackpack2 (Beta-0.8 if you believe the release notes) In the simplify: taste of vanilla (technic pack) RC1.5 I was able to recreate this dupe using several different backpacks in multiplayer.

**Comment by xKillerbees** [comment]
I also would like to confirm this issue.

**Comment by MrWisski** [comment]
Can also confirm this is an issue, but only when the backpack is being worn.

However, I can also give you the fix :
ContainerBackpack.java, onContainerClosed() needs to update the crafting grid by calling this.onCraftMatrixChanged(craftMatrix); - currently, this isn't being done, and the last crafting result persists between opening/closing (when being worn). Updating the craftMatrix after emptying it will result in expected functionality (crafting result is emptied when the backpack is closed).

**Comment by Darkona** [comment]
Done. Fixed for next release.
