### ISSUE TITLE
Simplify Modpack Bug

### ISSUE THREAD

**Issue by TD23ASUS** [Darkona/AdventureBackpack2#60]
Okay, before you get started, I know this should go to the author of the modpack rather than you.

Okay, now we know that I'm an idiot, I wish to ask you something.

Now I'm going to deposit a issue thingy with the author right after this but I figured the author of the original mod could help me too... because sometimes I want to break Technic.... I want to break every bone in its goddamned body... BUUUUUTTTTT I should probably get to the question.

I have tried many times to equip various backpacks from your mod but to no avail... I can use them by placing them... but I want the benefits of a Bat Backpack.... :/

Okay... so if you have any ideas... it'd be appreciated, but don't sweat too much... I'm gonna submit this to the modpack author.

TY, TD23ASUS

**Comment by Darkona** [comment]
See the wiki
