### ISSUE TITLE
Dissapearing backpacks...

### ISSUE THREAD

**Issue by xaleb** [Darkona/AdventureBackpack2#61]
So, I'm using the zombie pigman backpack and I've died to a creeper. I'm using x-ray mods, and such to find it due to the fact after the death it was suppose to turn into a block. However, there doesn't seem to be any luck. Is there an issue with backpacks just vanishing if there's not a possible block to place it or something? It's just this backpack in particular..I can find any others easy..and I know they aren't susceptible to explosions..(Tried) Also are there different ids for every backpack? I'd like to know the structure if possible. Thanks.

**Comment by xaleb** [comment]
Update: Only the zombie pigman one dissapears after being blown up in a certain spot by a creeper..Also refer to my fire resistance post..The pigman backpack seems to be bugged..

**Comment by MrabEzreb** [comment]
AHHH, the creepers. This happens with openblocks graves aswell. Creepers deal damage first, killing you, and THEN they destroy blocks. So, you die, backpack drops, and then it gets blown up. Sad, but true :(

**Comment by xaleb** [comment]
So creepers can destroy backpacks? But I used tnt, and it failed...

**Comment by MrabEzreb** [comment]
right, tnt and creepers work differently
this is vanilla that does this
idk about tnt, but creepers deal damage, then destroy blocks

**Comment by shadoxxhd** [comment]
i lost a backpack when i died from a infernal skeleton...

**Comment by Darkona** [comment]
Backpacks are indestructible by creeper explosions. But it places somewhere nearby when you die... above or below and at about 12 blocks square.
