### ISSUE TITLE
I can't use the backpack

### ISSUE THREAD

**Issue by stefy97100** [Darkona/AdventureBackpack2#62]
Hi, i'm using your mod on a server but i can't put the backpack on the armor. The piston boots works, the backpack not... why?

**Comment by MrabEzreb** [comment]
The backpack doesnt go into the armor slot.
To put the backpack on, right click with it in your hand and click on the button on the bottom left.

**Comment by theblindbandet** [comment]
I do that but once I need it I can't get it off. What do I do?

**Comment by MrabEzreb** [comment]
press the b key to open up the backpack, then press the same button

**Comment by theblindbandet** [comment]
Ohhh... Thanks!
