### ISSUE TITLE
FIRE RESISTANCE not working?

### ISSUE THREAD

**Issue by xaleb** [Darkona/AdventureBackpack2#64]
Does this mod alter fire resistance in any way? I can't swim in lava when it is applied..

UPDATE: THIS ONLY APPLIES WHEN I'M WEARING THE PIGMAN BACKPACK. I think you need to look over that backpack in particular..

**Comment by Darkona** [comment]
Working on the way effects are applied.

**Comment by Darkona** [comment]
Fixed for Beta-0.8d
