### ISSUE TITLE
Ocelot Backpack I cant wear it

### ISSUE THREAD

**Issue by LocoMinerDad** [Darkona/AdventureBackpack2#68]
In regular inventory there isnt any spot by the armor to wear it. I see the camping inventory tab and click it. I tried all the tabs but it doesnt work. There is a back pack slot but it doesnt  go there. What am I missing?

Thank you

**Comment by MrabEzreb** [comment]
I actually solved this for somebody else.
put on backpack: right click the backpack into the air, then click the button on the bottom left
take off backpack: press "B", then click the button on the bottom left
It doesn't go into a slot :P

**Comment by Darkona** [comment]
People would do great by reading the wiki.
