### ISSUE TITLE
Regeneration Effect from drinking Water Glitches

### ISSUE THREAD

**Issue by Flexico** [Darkona/AdventureBackpack2#70]
When I drink water from my hose, it gives me a brief Regeneration effect, but when it reaches "0:00" it sticks -- I no longer actually regenerate, but the effect remains visible in my inventory screen and my hearts keep bouncing.

**Comment by Darkona** [comment]
I'm aware of this. Its a general problem of the way effects are applied. 
I'm slapping myself while I write this.

**Comment by Darkona** [comment]
Fixed for Beta-0.8d
