### ISSUE TITLE
ArrayOutOfBounds Crash 

### ISSUE THREAD

**Issue by ElanHR** [Darkona/AdventureBackpack2#71]
Time: 3/19/15 2:12 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 46, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:674)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:651)
	at com.darkona.adventurebackpack.client.gui.GuiAdvBackpack.func_73869_a(GuiAdvBackpack.java:248)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:319)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:674)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:651)
	at com.darkona.adventurebackpack.client.gui.GuiAdvBackpack.func_73869_a(GuiAdvBackpack.java:248)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:319)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['isep'/27468, l='MpServer', x=-214.80, y=62.62, z=1908.75], EntityOtherPlayerMP['PhiloandGunge'/28286, l='MpServer', x=-214.31, y=72.00, z=1901.69]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-760,64,668), Chunk: (at 8,4,12 in -48,41; contains blocks -768,0,656 to -753,255,671), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 3244414 game time, 3288618 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntityZombie['Zombie'/30215, l='MpServer', x=-208.11, y=72.00, z=1894.33], MoCEntityKitty['Kitty'/27914, l='MpServer', x=-263.78, y=69.00, z=1899.13], EntityPainting['Painting'/27916, l='MpServer', x=-232.94, y=51.00, z=1892.00], MoCEntityAnt['Ant'/27917, l='MpServer', x=-133.53, y=63.00, z=1910.53], MoCEntityRaccoon['Raccoon'/27919, l='MpServer', x=-175.25, y=69.00, z=1892.59], MoCEntityCricket['Cricket'/27921, l='MpServer', x=-151.47, y=70.00, z=1873.81], EntityCreeper['Creeper'/30238, l='MpServer', x=-280.50, y=19.00, z=1924.50], EntityWisp['Wisp'/28973, l='MpServer', x=-190.94, y=31.09, z=1932.44], EntitySkeleton['Skeleton'/30263, l='MpServer', x=-220.06, y=42.00, z=1943.47], EntityCreeper['Creeper'/30008, l='MpServer', x=-211.97, y=72.00, z=1899.63], EntitySkeleton['Skeleton'/30016, l='MpServer', x=-160.44, y=65.00, z=1944.03], MoCEntitySnake['Snake'/28231, l='MpServer', x=-295.00, y=71.00, z=1869.00], MoCEntityRat['Rat'/30295, l='MpServer', x=-245.03, y=68.00, z=1922.25], EntityPech['Pech Stalker'/30300, l='MpServer', x=-194.69, y=66.00, z=1929.84], EntityClientPlayerMP['isep'/27468, l='MpServer', x=-214.80, y=62.62, z=1908.75], EntityPech['Pech Forager'/30301, l='MpServer', x=-211.25, y=64.00, z=1938.28], MoCEntityFishy['Fishy'/27486, l='MpServer', x=-149.73, y=61.00, z=1987.24], MoCEntityFishy['Fishy'/27487, l='MpServer', x=-149.85, y=61.00, z=1986.65], MoCEntityRay['Ray'/27488, l='MpServer', x=-149.10, y=61.00, z=1989.00], MoCEntityBee['Bee'/27489, l='MpServer', x=-157.38, y=73.00, z=1990.78], MoCEntityRay['Ray'/27494, l='MpServer', x=-154.91, y=60.25, z=1981.10], MoCEntityRay['Ray'/27495, l='MpServer', x=-154.91, y=60.00, z=1981.10], EntityWisp['Wisp'/27496, l='MpServer', x=-180.88, y=22.09, z=1949.47], MoCEntityKitty['Kitty'/27497, l='MpServer', x=-187.56, y=68.00, z=1964.13], EntityCreeper['Creeper'/29290, l='MpServer', x=-225.50, y=49.00, z=1871.03], EntityChicken['Chicken'/27502, l='MpServer', x=-235.47, y=67.00, z=1977.44], EntityZombie['Zombie'/30062, l='MpServer', x=-293.88, y=51.00, z=1951.41], MoCEntityMole['Mole'/27503, l='MpServer', x=-222.50, y=66.19, z=1953.50], MoCEntityRaccoon['Raccoon'/27504, l='MpServer', x=-210.56, y=66.00, z=1969.69], MoCEntityKitty['Kitty'/27505, l='MpServer', x=-143.56, y=62.53, z=1959.00], EntityPainting['Painting'/27916, l='MpServer', x=-232.94, y=51.00, z=1892.00], EntityOtherPlayerMP['PhiloandGunge'/28286, l='MpServer', x=-214.31, y=72.00, z=1901.69], EntityItem['item.item.egg'/30344, l='MpServer', x=-174.88, y=68.13, z=1933.75], EntityPig['Pig'/28304, l='MpServer', x=-175.47, y=88.00, z=1829.66], MoCEntityRaccoon['Raccoon'/28305, l='MpServer', x=-184.97, y=74.00, z=1815.59], MoCEntityBird['Bird'/27539, l='MpServer', x=-247.78, y=65.00, z=1960.22], EntitySlime['Slime'/27540, l='MpServer', x=-228.69, y=25.00, z=1938.69], EntityPig['Pig'/28308, l='MpServer', x=-287.19, y=78.00, z=1835.56], MoCEntityBee['Bee'/28309, l='MpServer', x=-151.84, y=71.00, z=1836.56], EntityWisp['Wisp'/27542, l='MpServer', x=-183.81, y=44.97, z=1927.91], MoCEntityFirefly['Firefly'/28310, l='MpServer', x=-141.72, y=66.00, z=1846.53], EntityWisp['Wisp'/27543, l='MpServer', x=-191.53, y=49.00, z=1935.53], EntityChicken['Chicken'/27544, l='MpServer', x=-176.47, y=68.00, z=1933.53], EntityWisp['Wisp'/27546, l='MpServer', x=-195.50, y=39.17, z=1929.61], MoCEntityButterfly['ButterFly'/28318, l='MpServer', x=-312.16, y=81.00, z=1848.28], EntityOtherPlayerMP['PhiloandGunge'/28286, l='MpServer', x=-213.91, y=60.00, z=1904.31], MoCEntityRay['Ray'/27571, l='MpServer', x=-133.94, y=57.00, z=1933.03], MoCEntityRay['Ray'/27572, l='MpServer', x=-135.09, y=56.65, z=1931.91], MoCEntityKitty['Kitty'/27573, l='MpServer', x=-140.53, y=64.00, z=1926.50], MoCEntityKitty['Kitty'/27581, l='MpServer', x=-275.63, y=62.53, z=1985.31], EntityZombie['Zombie'/29885, l='MpServer', x=-166.50, y=30.00, z=1981.50], EntityHorse['Horse'/27582, l='MpServer', x=-282.13, y=66.00, z=1969.03], MoCEntityHorse['WildHorse'/27583, l='MpServer', x=-221.28, y=64.00, z=1919.28], MoCEntityRaccoon['Raccoon'/28095, l='MpServer', x=-235.22, y=70.00, z=1859.66], MoCEntityKitty['Kitty'/27584, l='MpServer', x=-159.56, y=64.00, z=1915.00], EntitySheep['Sheep'/27589, l='MpServer', x=-264.88, y=68.00, z=1939.66], EntityCreeper['Creeper'/30149, l='MpServer', x=-278.50, y=55.00, z=1906.50], EntitySlime['Slime'/28102, l='MpServer', x=-230.69, y=25.00, z=1924.31], EntityChicken['Chicken'/27593, l='MpServer', x=-252.19, y=67.00, z=1918.03], EntityCreeper['Creeper'/30153, l='MpServer', x=-273.50, y=63.00, z=1929.50], MoCEntityRay['Ray'/27595, l='MpServer', x=-132.88, y=62.00, z=1929.11], EntityItem['item.item.rottenFlesh'/30412, l='MpServer', x=-251.47, y=69.13, z=1962.00], EntityChicken['Chicken'/27598, l='MpServer', x=-272.59, y=67.00, z=1958.63], EntityHorse['Horse'/28111, l='MpServer', x=-260.28, y=68.00, z=1862.09], MoCEntityKitty['Kitty'/27600, l='MpServer', x=-142.63, y=64.00, z=1910.94], EntityItem['item.item.rottenFlesh'/29136, l='MpServer', x=-206.88, y=38.13, z=1897.63], MoCEntityGoat['Goat'/28112, l='MpServer', x=-259.13, y=69.00, z=1857.00], EntityWisp['Wisp'/28883, l='MpServer', x=-205.50, y=21.09, z=1928.47], EntityZombie['Zombie'/29653, l='MpServer', x=-225.69, y=48.00, z=1867.78], EntityWitherSkullCrawler['Wither Skull Crawler'/30426, l='MpServer', x=-246.75, y=67.00, z=1961.41], EntityPig['Pig'/27867, l='MpServer', x=-141.03, y=65.00, z=1875.16], EntityItem['item.item.rottenFlesh'/30427, l='MpServer', x=-253.19, y=68.13, z=1966.88], MoCEntityKitty['Kitty'/27868, l='MpServer', x=-130.13, y=66.00, z=1891.28], EntityChicken['Chicken'/28130, l='MpServer', x=-287.63, y=72.00, z=1860.25], EntityCow['Cow'/28131, l='MpServer', x=-273.13, y=70.00, z=1864.94], EntitySkeleton['Skeleton'/30179, l='MpServer', x=-234.66, y=31.00, z=1898.66], EntityPig['Pig'/28132, l='MpServer', x=-286.88, y=76.00, z=1857.94], EntityZombie['Zombie'/30180, l='MpServer', x=-231.53, y=33.00, z=1902.03], MoCEntityMaggot['Maggot'/27624, l='MpServer', x=-289.69, y=67.00, z=1961.19], EntityItem['item.tile.flowers.anemone'/30441, l='MpServer', x=-215.38, y=72.78, z=1901.47], EntityItem['item.tile.dirt.default'/30442, l='MpServer', x=-210.28, y=70.78, z=1898.34], EntityItem['item.tile.sapling.oak'/30443, l='MpServer', x=-215.50, y=74.13, z=1899.72], EntityItem['item.tile.dirt.default'/30444, l='MpServer', x=-210.56, y=71.78, z=1897.19], EntityItem['item.tile.dirt.default'/30445, l='MpServer', x=-210.31, y=71.63, z=1898.44], EntityChicken['Chicken'/27630, l='MpServer', x=-281.53, y=68.00, z=1931.53], MoCEntityRaccoon['Raccoon'/28142, l='MpServer', x=-135.41, y=64.00, z=1861.66], EntityItem['item.tile.dirt.default'/30446, l='MpServer', x=-210.47, y=71.59, z=1900.34], EntityPig['Pig'/28143, l='MpServer', x=-170.06, y=72.00, z=1857.16], EntityItem['item.item.seeds'/30447, l='MpServer', x=-214.44, y=72.78, z=1902.66], MoCEntityCricket['Cricket'/27632, l='MpServer', x=-269.25, y=69.00, z=1909.47], EntityItem['item.tile.dirt.default'/30448, l='MpServer', x=-212.69, y=70.81, z=1898.38], EntityItem['item.tile.dirt.default'/30449, l='MpServer', x=-209.44, y=71.25, z=1898.75], EntityOtherPlayerMP['PhiloandGunge'/28286, l='MpServer', x=-213.56, y=60.00, z=1902.31], EntityItem['item.tile.dirt.default'/30450, l='MpServer', x=-209.19, y=71.78, z=1899.38], EntityItem['item.tile.dirt.default'/30451, l='MpServer', x=-209.50, y=71.28, z=1900.19], EntityItem['item.tile.dirt.default'/30452, l='MpServer', x=-211.25, y=70.44, z=1900.25], EntityItem['item.item.egg'/30202, l='MpServer', x=-255.47, y=65.13, z=1917.34], EntityOtherPlayerMP['PhiloandGunge'/28286, l='MpServer', x=-214.31, y=72.00, z=1901.69], EntityItem['item.item.egg'/30207, l='MpServer', x=-271.56, y=66.13, z=1959.81]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 404134216 bytes (385 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 104
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 50 mods loaded, 50 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Aquaculture{1.2.3} [Aquaculture] (Aquaculture-1.7.10-1.2.5.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CaveBiomes{0.01} [CaveBiomes] (CaveBiomes_Beta5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	colorfularmor{1.7.10-2.5} [Colorful Armor] (colorfularmor-1.7.10-2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	props{1.12} [Decocraft] (Decocraft-v1.12b_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HardcoreEnderExpansion{1.7} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_FairPlay_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JourneyMapServer{1.0.2_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.3_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	millenaire{5.2.0b5} [Mill?©naire] (millenaire-5.2b5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	modularpots{1.7.10.14} [Modular Flower Pots] (ModularPots-1.7.10.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	rancraftpenguins{1.7.10q} [Rancraft Penguins] (rancraftpenguins-1.7.10q.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Roguelike{1.3.6} [Roguelike Dungeons] (Roguelike-Dungeons-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	punt{1.7.10-10.13.0-14.0} [Punt] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	whitehall{1.7.10-10.13.0-14.0} [Whitehall] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	hoy{1.7.10-10.13.0-14.0} [Hoy] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	smallboats{1.7.10-10.13.0-14.0} [SmallBoats (base)] (Small-Boats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{2.3.4} [The Twilight Forest] (twilightforest-1.7.10-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX TITAN/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by Darkona** [comment]
I have no idea what to do about this, but hopefully it'll fix itself while working on the lag bug. I think it's related.
