### ISSUE TITLE
Missing Textures on Standard Backpack

### ISSUE THREAD

**Issue by TheWhiteWolves** [Darkona/AdventureBackpack2#77]
Using adventurebackpack-1.7.10-0.8b.jar and forge 10.13.2.1291, it seems that theres a texture linking problem on your standard backpack as it not finding the texture for it (see the screenshots below).

This is only on the Standard backpack btw, the rest are fine.

![2015-04-05_10 40 29](https://cloud.githubusercontent.com/assets/1471503/6996447/1d425f80-db81-11e4-9ad7-827c0d584ba2.png)
![2015-04-05_10 40 35](https://cloud.githubusercontent.com/assets/1471503/6996446/1d425c6a-db81-11e4-8928-26c5a447a8a7.png)

**Comment by FabioZumbi12** [comment]
With me too :/

**Comment by wizard04wsu** [comment]
Same thing happened to me after a few days. I removed the mod, downloaded a new copy, and added it back to no effect. In the NEI list of items, two are pink:

- blockAdventureBackpack.name (#0165) 165  
adventurebackpack:blockBackpack
- Adventure Backpack (#4100) 4100  
adventurebackpack:adventureBackpackStandard

**Comment by Darkona** [comment]
It's a missing textures problem. I purposely left some textures "for later" and then life happened. Always finish your homework, kids.

It'll be fixed in next version, no excuses.
