### ISSUE TITLE
KeepInventory drop the backpack

### ISSUE THREAD

**Issue by FabioZumbi12** [Darkona/AdventureBackpack2#85]
Can you add an option to do not drop the BackPack when die??

I am using with gamerule "keepinventory" i dont want to drop the backpack

**Comment by Sasikaa** [comment]
Oh YES! And drop the copter pack when Die, in the nether into Lava... Please Make. Or Enchantable, and working the enchant not dropping this 2 items. Please...

**Comment by Darkona** [comment]
Fixing for next release.

**Comment by Darkona** [comment]
Closed along with #50.
Fixed in next version.
