### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by runescapejon** [Darkona/AdventureBackpack2#91]
Hey man can you fix this bug where you dont see your backpack on your back on a bungeecord server

**Comment by Darkona** [comment]
Ehm... I'm gonna need @SpigotMC for this one.

**Comment by runescapejon** [comment]
ohh okay

**Comment by Darkona** [comment]
Question, is it only a visual bug or the backpack does not work properly?

**Comment by runescapejon** [comment]
does not work properly

**Comment by Darkona** [comment]
Please explain in detail what the problem is, then. What works, what doesn't, what do you do to make it happen/not happen.

**Comment by runescapejon** [comment]
okay when i have the backpack on and i don't see it and tried setting my keys sets and it dont work i cant open my backpack on my back but keep in mind this while time i dont see it the backpack, backpack only works when you place it down and then you can open it from there but if you place it griefprevention dont protected your backpack so anyone can access the backpack

**Comment by Tommycop007** [comment]
look just curious how do you but the backpack on i can't figure it out
