### ISSUE TITLE
Cross mod incompatibility with Automagy

### ISSUE THREAD

**Issue by kayila** [Darkona/AdventureBackpack2#92]
Both mods introduce milk, but the two forms are incompatible with each other. Any chance you could look up milk in the liquid dictionary before adding it?

**Comment by Darkona** [comment]
I remember reading the code for the Forge FluidRegistry and it should make a lookup for a fluid when you register a new one, so it didn't make a duplicate. Maybe something changed in the new forge, or Automancy does something weird.

Checking that today.

**Comment by Darkona** [comment]
Checked.
It is not this mod's fault, please inform Automagy's modder of the incompatibility.
He is registering a "fluidmilk" and/or looking for such a fluid. Looking at it, that milk fluid isn't properly set in the Fluid Registry, and creates some nasty effects on the environment when spilled with a bucket.

I tried looking for that particular fluid, but it isn't the same so my milk and that milk are different fluids.

Won't fix for the time being.
