### ISSUE TITLE
Boat

### ISSUE THREAD

**Issue by killerscorpion** [Darkona/AdventureBackpack2#93]
Seriously, how do you craft the inflatable boat. Nothin on the wiki about it and nothing in your changelogs explaining how to obtain them.

**Comment by Darkona** [comment]
They're not complete, still a WIP item.
Also the world isn't ready.

**Comment by killerscorpion** [comment]
oh ok. Out of curiosity whats wrong with them? the non motorized version seems to work fine in creative.
